# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cf_autofly.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1018, 816)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textEdit_uri = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_uri.setGeometry(QtCore.QRect(60, 10, 281, 31))
        self.textEdit_uri.setObjectName("textEdit_uri")
        self.label_uri = QtWidgets.QLabel(self.centralwidget)
        self.label_uri.setGeometry(QtCore.QRect(10, 10, 80, 31))
        self.label_uri.setObjectName("label_uri")
        self.button_connect = QtWidgets.QPushButton(self.centralwidget)
        self.button_connect.setGeometry(QtCore.QRect(370, 10, 106, 30))
        self.button_connect.setObjectName("button_connect")
        self.button_takeoff = QtWidgets.QPushButton(self.centralwidget)
        self.button_takeoff.setGeometry(QtCore.QRect(570, 10, 106, 30))
        self.button_takeoff.setObjectName("button_takeoff")
        self.button_land = QtWidgets.QPushButton(self.centralwidget)
        self.button_land.setGeometry(QtCore.QRect(790, 10, 111, 30))
        self.button_land.setObjectName("button_land")
        self.plot_widget = QtWidgets.QWidget(self.centralwidget)
        self.plot_widget.setGeometry(QtCore.QRect(10, 190, 601, 561))
        self.plot_widget.setObjectName("plot_widget")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(230, 760, 651, 31))
        self.label_7.setObjectName("label_7")
        self.listView = QtWidgets.QListView(self.centralwidget)
        self.listView.setGeometry(QtCore.QRect(650, 190, 351, 561))
        self.listView.setObjectName("listView")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 181, 21))
        self.label_2.setObjectName("label_2")
        self.doubleSpinBox_x = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_x.setGeometry(QtCore.QRect(180, 60, 71, 21))
        self.doubleSpinBox_x.setObjectName("doubleSpinBox_x")
        self.label_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_1.setGeometry(QtCore.QRect(140, 60, 80, 21))
        self.label_1.setObjectName("label_1")
        self.doubleSpinBox_y = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_y.setGeometry(QtCore.QRect(330, 60, 71, 21))
        self.doubleSpinBox_y.setObjectName("doubleSpinBox_y")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(300, 60, 80, 21))
        self.label_4.setObjectName("label_4")
        self.doubleSpinBox_z = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_z.setGeometry(QtCore.QRect(490, 60, 71, 21))
        self.doubleSpinBox_z.setObjectName("doubleSpinBox_z")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(460, 60, 80, 21))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(620, 60, 80, 21))
        self.label_6.setObjectName("label_6")
        self.doubleSpinBox_yaw = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_yaw.setGeometry(QtCore.QRect(680, 60, 71, 21))
        self.doubleSpinBox_yaw.setObjectName("doubleSpinBox_yaw")
        self.button_send = QtWidgets.QPushButton(self.centralwidget)
        self.button_send.setGeometry(QtCore.QRect(790, 50, 111, 41))
        self.button_send.setObjectName("button_send")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(10, 110, 261, 21))
        self.label_8.setObjectName("label_8")
        self.button_traj_set = QtWidgets.QPushButton(self.centralwidget)
        self.button_traj_set.setGeometry(QtCore.QRect(190, 100, 91, 41))
        self.button_traj_set.setObjectName("button_traj_set")
        self.button_traj_follow = QtWidgets.QPushButton(self.centralwidget)
        self.button_traj_follow.setGeometry(QtCore.QRect(310, 100, 91, 41))
        self.button_traj_follow.setObjectName("button_traj_follow")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(660, 160, 131, 21))
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1018, 26))
        self.menubar.setObjectName("menubar")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuMode = QtWidgets.QMenu(self.menubar)
        self.menuMode.setObjectName("menuMode")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionPosition_Mode = QtWidgets.QAction(MainWindow)
        self.actionPosition_Mode.setObjectName("actionPosition_Mode")
        self.actionHover_mode = QtWidgets.QAction(MainWindow)
        self.actionHover_mode.setObjectName("actionHover_mode")
        self.actionZ_distance_mode = QtWidgets.QAction(MainWindow)
        self.actionZ_distance_mode.setObjectName("actionZ_distance_mode")
        self.actionPosition_Mode_2 = QtWidgets.QAction(MainWindow)
        self.actionPosition_Mode_2.setObjectName("actionPosition_Mode_2")
        self.actionHover_Mode = QtWidgets.QAction(MainWindow)
        self.actionHover_Mode.setObjectName("actionHover_Mode")
        self.actionZdistance_Mode = QtWidgets.QAction(MainWindow)
        self.actionZdistance_Mode.setObjectName("actionZdistance_Mode")
        self.actionRPY_MOde = QtWidgets.QAction(MainWindow)
        self.actionRPY_MOde.setObjectName("actionRPY_MOde")
        self.menuMode.addSeparator()
        self.menuMode.addSeparator()
        self.menuMode.addAction(self.actionPosition_Mode_2)
        self.menuMode.addAction(self.actionHover_Mode)
        self.menuMode.addAction(self.actionZdistance_Mode)
        self.menuMode.addAction(self.actionRPY_MOde)
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuMode.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Crazyflie Autofly"))
        self.textEdit_uri.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">radio://0/80/2M</p></body></html>"))
        self.label_uri.setText(_translate("MainWindow", "URI:"))
        self.button_connect.setText(_translate("MainWindow", "Connect"))
        self.button_takeoff.setText(_translate("MainWindow", "Take Off"))
        self.button_land.setText(_translate("MainWindow", "Land"))
        self.label_7.setText(_translate("MainWindow", "Keyboard control:  up \"w\", down \"s\",   left \"a\", right \"d\", forward \"q\", back \"e\"          "))
        self.label_2.setText(_translate("MainWindow", "Send Point:"))
        self.label_1.setText(_translate("MainWindow", "x="))
        self.label_4.setText(_translate("MainWindow", "y="))
        self.label_5.setText(_translate("MainWindow", "z="))
        self.label_6.setText(_translate("MainWindow", "yaw="))
        self.button_send.setText(_translate("MainWindow", "Go"))
        self.label_8.setText(_translate("MainWindow", "Trajectory follow: "))
        self.button_traj_set.setText(_translate("MainWindow", "Set"))
        self.button_traj_follow.setText(_translate("MainWindow", "Follow"))
        self.label.setText(_translate("MainWindow", "UAV status"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.menuMode.setTitle(_translate("MainWindow", "Mode"))
        self.actionPosition_Mode.setText(_translate("MainWindow", "Position Mode"))
        self.actionHover_mode.setText(_translate("MainWindow", "Hover mode"))
        self.actionZ_distance_mode.setText(_translate("MainWindow", "Z distance mode"))
        self.actionPosition_Mode_2.setText(_translate("MainWindow", "Position Mode"))
        self.actionHover_Mode.setText(_translate("MainWindow", "Hover Mode"))
        self.actionZdistance_Mode.setText(_translate("MainWindow", "Zdistance Mode"))
        self.actionRPY_MOde.setText(_translate("MainWindow", "Attitude Mode"))

